#!/bin/sh

export AMBERHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
export XENVIRONMENT="$AMBERHOME/dat/XaLeap_wcl"

"$AMBERHOME/bin/xaLeap" \
           -I"$AMBERHOME/dat/leap/prep" \
           -I"$AMBERHOME/dat/leap/lib" \
           -I"$AMBERHOME/dat/leap/parm" \
           -I"$AMBERHOME/dat/leap/cmd" \
            $*
