#define cudaDeviceMapHost hipDeviceMapHost
#define cudaDeviceProp hipDeviceProp_t
#define cudaDeviceReset hipDeviceReset
#define cudaDeviceSynchronize hipDeviceSynchronize
#define cudaError_t hipError_t
#define cudaFree hipFree
#define cudaGetDevice hipGetDevice
#define cudaGetDeviceCount hipGetDeviceCount
#define cudaGetDeviceProperties hipGetDeviceProperties
#define cudaFreeHost hipHostFree
#define cudaHostFree hipHostFree
#define cudaHostAlloc hipHostMalloc
#define cudaHostAllocMapped hipHostMallocMapped
#define cudaHostMalloc hipHostMalloc
#define cudaHostMallocMapped hipHostMallocMapped
#define cudaLaunchKernelGGL hipLaunchKernelGGL
#define cudaMalloc hipMalloc
#define cudaMemcpy hipMemcpy
#define cudaMemcpyDeviceToHost hipMemcpyDeviceToHost
#define cudaMemcpyHostToDevice hipMemcpyHostToDevice
#define cudaMemcpyToSymbol hipMemcpyToSymbol
#define cudaMemset hipMemset
#define cudaSetDeviceFlags hipSetDeviceFlags
#define cudaSuccess hipSuccess

#define curandState hiprandState
#define curandState_t hiprandState_t
#define curand_init hiprand_init
#define curand_normal hiprand_normal
