# (1)  Location of the installation:

BINDIR=$(AMBERHOME)/bin
INCDIR=

LDFLAGS= $(CUSTOMBUILDFLAGS)

SFX=
OSFX=.o

NETCDF=
NETCDFLIB=
NETCDFINC=

#PMEMD Specific build flags
PMEMD_F90=gfortran -DPUBFFT -DGNU_HACKS
PMEMD_FOPTFLAGS=-O3 -mtune=native
PMEMD_CC=gcc
PMEMD_COPTFLAGS=-O3 -mtune=native -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE 
PMEMD_FLIBSF= 
PMEMD_LD= gfortran 
