#ifndef HIP_DEFINITIONS_H
#  define HIP_DEFINITIONS_H
#  if defined(AMBER_PLATFORM_AMD)
// special
#    define __CUDACC_VER_MAJOR__ 10
// generated
#    define cublas hipblas
#    define cublasCreate hipblasCreate
#    define cublasDestroy hipblasDestroy
#    define cublasHandle_t hipblasHandle_t
#    define cublasSasum hipblasSasum
#    define cublasSaxpy hipblasSaxpy
#    define cublasScopy hipblasScopy
#    define cublasSdot hipblasSdot
#    define cublasSscal hipblasSscal
#    define cublasStatus_t hipblasStatus_t
#    define cudaComputeModeProhibited hipComputeModeProhibited
#    define cudaDeviceProp hipDeviceProp_t
#    define cudaDeviceReset hipDeviceReset
#    define cudaDeviceSynchronize hipDeviceSynchronize
#    define cudaError_t hipError_t
#    define cudaFree hipFree
#    define cudaGetDevice hipGetDevice
#    define cudaGetDeviceCount hipGetDeviceCount
#    define cudaGetDeviceProperties hipGetDeviceProperties
#    define cudaGetErrorString hipGetErrorString
#    define cudaGetLastError hipGetLastError
#    define cudaMalloc hipMalloc
#    define cudaMallocManaged hipMallocManaged
#    define cudaAlloc hipAlloc
#    define cudaAllocManaged hipAllocManaged
#    define cudaMemcpy hipMemcpy
#    define cudaMemcpyDeviceToDevice hipMemcpyDeviceToDevice
#    define cudaMemcpyDeviceToHost hipMemcpyDeviceToHost
#    define cudaMemcpyHostToDevice hipMemcpyHostToDevice
#    define cudaMemcpyToSymbol hipMemcpyToSymbol
#    define cudaMemcpyFromSymbol hipMemcpyFromSymbol
#    define cudaMemPrefetchAsync hipMemPrefetchAsync
#    define cudaSetDevice hipSetDevice
#    define cusparseCreate hipsparseCreate
#    define cusparseCreateMatDescr hipsparseCreateMatDescr
#    define cusparseDestroy hipsparseDestroy
#    define cusparseHandle_t hipsparseHandle_t
#    define cusparseMatDescr_t hipsparseMatDescr_t
#    define cusparseScsrmv hipsparseScsrmv
#    define cusparseSetMatIndexBase hipsparseSetMatIndexBase
#    define cusparseSetMatType hipsparseSetMatType
#    define cusparseStatus_t hipsparseStatus_t
#    define cudaSuccess hipSuccess
#    define CUBLAS_STATUS_ALLOC_FAILED HIPBLAS_STATUS_ALLOC_FAILED
#    define CUBLAS_STATUS_ARCH_MISMATCH HIPBLAS_STATUS_ARCH_MISMATCH
#    define CUBLAS_STATUS_EXECUTION_FAILED HIPBLAS_STATUS_EXECUTION_FAILED
#    define CUBLAS_STATUS_INTERNAL_ERROR HIPBLAS_STATUS_INTERNAL_ERROR
#    define CUBLAS_STATUS_INVALID_VALUE HIPBLAS_STATUS_INVALID_VALUE
#    define CUBLAS_STATUS_LICENSE_ERROR HIPBLAS_STATUS_LICENSE_ERROR
#    define CUBLAS_STATUS_MAPPING_ERROR HIPBLAS_STATUS_MAPPING_ERROR
#    define CUBLAS_STATUS_NOT_INITIALIZED HIPBLAS_STATUS_NOT_INITIALIZED
#    define CUBLAS_STATUS_NOT_SUPPORTED HIPBLAS_STATUS_NOT_SUPPORTED
#    define CUBLAS_STATUS_SUCCESS HIPBLAS_STATUS_SUCCESS
#    define CUSPARSE_STATUS_ALLOC_FAILED HIPSPARSE_STATUS_ALLOC_FAILED
#    define CUSPARSE_STATUS_ARCH_MISMATCH HIPSPARSE_STATUS_ARCH_MISMATCH
#    define CUSPARSE_STATUS_EXECUTION_FAILED HIPSPARSE_STATUS_EXECUTION_FAILED
#    define CUSPARSE_STATUS_INTERNAL_ERROR HIPSPARSE_STATUS_INTERNAL_ERROR
#    define CUSPARSE_STATUS_INVALID_VALUE HIPSPARSE_STATUS_INVALID_VALUE
#    define CUSPARSE_STATUS_MAPPING_ERROR HIPSPARSE_STATUS_MAPPING_ERROR
#    define CUSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED HIPSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED
#    define CUSPARSE_STATUS_NOT_INITIALIZED HIPSPARSE_STATUS_NOT_INITIALIZED
#    define CUSPARSE_STATUS_SUCCESS HIPSPARSE_STATUS_SUCCESS
#    define CUSPARSE_STATUS_ZERO_PIVOT HIPSPARSE_STATUS_ZERO_PIVOT
#    define CUSPARSE_INDEX_BASE_ZERO HIPSPARSE_INDEX_BASE_ZERO
#    define CUSPARSE_MATRIX_TYPE_GENERAL HIPSPARSE_MATRIX_TYPE_GENERAL
#    define CUSPARSE_OPERATION_NON_TRANSPOSE HIPSPARSE_OPERATION_NON_TRANSPOSE
#  endif // AMBER_PLATFORM_AMD
#endif // HIP_DEFINITIONS_H
