# make.inc template.  
#
# CMake will substitute variables of the form @...@.
#

# The name of the libraries to be created/linked to
XBLASLIB = libxblas.a
XBLASLIB_AMB = libxblas-amb.a

# CC is the C compiler, normally invoked with options CFLAGS.
# LINKER and LDFLAGS function as CC and CFLAGS, but for linking stages.
CC = @CMAKE_C_COMPILER@
CFLAGS = @XBLAS_CFLAGS@
LINKER = $(CC)
LDFLAGS = @CMAKE_EXE_LINKER_FLAGS@

# The archiver and the flag(s) to use when building archive (library)
# If your system has no ranlib, set RANLIB = echo.
ARCH         = ar
ARCHFLAGS    = cr
RANLIB       = @CMAKE_RANLIB@

# Extra libraries needed for xblas test code.
EXTRA_LIBS = @XBLAS_EXTRA_LIBS@

# M4 macro preprocessor.  Used to generate C sources.
M4 	= @M4@
M4_OPTS = @XBLAS_M4_OPTS@

# Indent program.  Used to prettify C source generated by M4.
INDENT	= :
INDENT_OPTS = 

