#!/bin/csh -f
echo " "
echo "  py_resp demo: CH3SCH3"
echo " "
echo " Running pyresp_gen.py "
$AMBERHOME/bin/pyresp_gen.py -i ../../../../examples/PyRESP/test/CH3SCH3-pyrespgen/CH3SCH3.dat -p chg -f1 1st.in -f2 2nd.in 

echo " RESP stage 1 "
$AMBERHOME/bin/py_resp.py -O \
		-i 1st.in \
		-o 1st.out \
		-s 1st.esp \
		-t 1st.chg \
		-e ../../../../examples/PyRESP/test/CH3SCH3-pyrespgen/CH3SCH3.dat			|| goto error

echo " RESP stage 2 "
$AMBERHOME/bin/py_resp.py -O \
		-i 2nd.in \
		-o 2nd.out \
		-q 1st.chg \
		-s 2nd.esp \
		-t 2nd.chg \
		-e ../../../../examples/PyRESP/test/CH3SCH3-pyrespgen/CH3SCH3.dat			|| goto error

foreach i (*in *out *chg *esp)
../../../dacdif -r 1e-6 $i.save $i
end
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)
